using AutoMapper;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Configuration;
using Moq;
using System.Diagnostics.CodeAnalysis;
using Web.Server.DTOs;
using Web.Server.Entities;
using Web.Server.Enums;
using Web.Server.Hubs;
using Web.Server.Mappers;
using Web.Server.Providers;
using Web.Server.Repositories;
using Web.Server.Services;

namespace Web.ServerTests.Services
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class MapPinServiceTests
    {
        private readonly Mock<IBeaconRailroadService> _beaconRailroadServiceMock = new();
        private readonly Mock<IHubClients> _hubClientsMock = new();
        private readonly Mock<IHubContext<NotificationHub>> _hubContextMock = new();
        private readonly Mock<IMapPinRepository> _mapPinRepositoryMock = new();
        private readonly Mock<ITimeProvider> _timeProviderMock = new();
        private readonly Mock<IClientProxy> _clientProxyMock = new();
        private readonly Mock<IMapPinHistoryService> _mapPinHistoryServiceMock = new();
        private readonly Mock<IConfiguration> _configurationMock = new();

        private MapPinService _service;
        private IMapper _mapper;

        private DateTime _currentDateTime;

        [TestInitialize]
        public void Setup()
        {
            _currentDateTime = DateTime.UtcNow;
            _timeProviderMock.Setup(tp => tp.UtcNow).Returns(_currentDateTime);

            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<AutoMapperProfile>();
            });
            _mapper = config.CreateMapper();

            _configurationMock.Setup(c => c.GetSection("ApplicationSettings:StationaryDirectionNullThresholdMinutes").Value)
                .Returns("360");

            _service = new MapPinService(
                _beaconRailroadServiceMock.Object,
                _hubContextMock.Object,
                _mapper,
                _mapPinRepositoryMock.Object,
                _timeProviderMock.Object,
                _mapPinHistoryServiceMock.Object,
                _configurationMock.Object
            );
        }

        [TestMethod]
        public async Task GetMapPinsAsync_ReturnsAllMapPins()
        {
            // Arrange
            var mapPins = new List<MapPin> { new MapPin { ID = 1, BeaconID = 1, SubdivisionId = 1 } };
            _mapPinRepositoryMock.Setup(r => r.GetAllAsync(null)).ReturnsAsync(mapPins);

            // Act
            var result = await _service.GetMapPinsAsync(null);

            // Assert
            Assert.AreEqual(mapPins, result);
        }

        [TestMethod]
        public async Task GetMapPinByIdAsync_ReturnsMapPin_WhenFound()
        {
            // Arrange
            var mapPin = new MapPin { ID = 1, BeaconID = 1, SubdivisionId = 1 };
            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(1)).ReturnsAsync(mapPin);

            // Act
            var result = await _service.GetMapPinByIdAsync(1);

            // Assert
            Assert.AreEqual(mapPin, result);
        }

        [TestMethod]
        public async Task GetMapPinByIdAsync_ReturnsNull_WhenNotFound()
        {
            // Arrange
            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(1)).ReturnsAsync((MapPin?)null);

            // Act
            var result = await _service.GetMapPinByIdAsync(1);

            // Assert
            Assert.IsNull(result);
        }

        [TestMethod]
        public async Task UpsertMapPin_CreateMapPin_MultiRailroad()
        {
            // Arrange
            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var WSORRugbyJunctionBeacon = TestData.WSOR_RugbyJunction_WI(_currentDateTime);

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = 23424,
                Source = "HOT",
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                Moving = true
            };

            // Hack: First railroad listed will be chosen because this is a mutli-railroad beacon
            // and the only other option is to not show the map pin at all.
            var beaconRailroads = new List<BeaconRailroad>
            {
                WSORRugbyJunctionBeacon, // Hack: First railroad will be chosen.
                CNRugbyJunctionBeacon
            };

            var expectedMapPinBeforeInsert = new MapPin
            {
                ID = 0, // New map pin, ID will be generated by the database.
                BeaconID = WSORRugbyJunctionBeacon.BeaconID,
                SubdivisionId = WSORRugbyJunctionBeacon.Subdivision.ID,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = WSORRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = telemetry.Source,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var expectedMapPinAfterInsert = new MapPin
            {
                ID = 234, // ID returned.
                BeaconID = WSORRugbyJunctionBeacon.BeaconID,
                SubdivisionId = WSORRugbyJunctionBeacon.Subdivision.ID,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = WSORRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = telemetry.Source,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            // This map pin is a guess based on the first railroad for the multi-railroad beacon. Due to a
            // hack in the code to temporarily provide a beacon rather than nothing, the map pin will
            // show the first railroad in the list, which in this test case is WSOR even though the telemetry
            // beacon ID came from the CN.
            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = 234,
                    Direction = null,
                    BeaconID = WSORRugbyJunctionBeacon.BeaconID,
                    BeaconName = WSORRugbyJunctionBeacon.Beacon.Name,
                    Railroad = WSORRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = WSORRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = WSORRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = WSORRugbyJunctionBeacon.Latitude,
                    Longitude = WSORRugbyJunctionBeacon.Longitude,
                    Milepost = WSORRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = telemetry.AddressID,
                            Source = telemetry.Source
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, WSORRugbyJunctionBeacon.Subdivision.RailroadID, 5))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(expectedMapPinBeforeInsert))
                .ReturnsAsync(expectedMapPinAfterInsert);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(expectedMapPinBeforeInsert), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Once);
        }

        [TestMethod]
        public async Task UpsertMapPin_CreateMapPin_SingleRailroad()
        {
            // Arrange
            var WSORRugbyJunctionBeacon = TestData.WSOR_RugbyJunction_WI(_currentDateTime);

            var telemetry = new Telemetry
            {
                BeaconID = WSORRugbyJunctionBeacon.BeaconID,
                AddressID = 23424,
                Source = "HOT",
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime
            };

            var beaconRailroads = new List<BeaconRailroad>
            {
                WSORRugbyJunctionBeacon
            };

            var expectedMapPinBeforeInsert = new MapPin
            {
                ID = 0, // New map pin, ID will be generated by the database.
                BeaconID = WSORRugbyJunctionBeacon.BeaconID,
                SubdivisionId = WSORRugbyJunctionBeacon.Subdivision.ID,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = WSORRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = telemetry.Source,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var expectedMapPinAfterInsert = expectedMapPinBeforeInsert.Clone();
            expectedMapPinAfterInsert.ID = 234;

            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = expectedMapPinAfterInsert.ID,
                    Direction = null,
                    BeaconID = WSORRugbyJunctionBeacon.BeaconID,
                    BeaconName = WSORRugbyJunctionBeacon.Beacon.Name,
                    Railroad = WSORRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = WSORRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = WSORRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = WSORRugbyJunctionBeacon.Latitude,
                    Longitude = WSORRugbyJunctionBeacon.Longitude,
                    Milepost = WSORRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = telemetry.AddressID,
                            Source = telemetry.Source
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, WSORRugbyJunctionBeacon.SubdivisionID, 5))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(expectedMapPinBeforeInsert))
                .ReturnsAsync(expectedMapPinAfterInsert);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(expectedMapPinBeforeInsert), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Once);
        }

        [TestMethod]
        public async Task UpsertMapPin_CreateMapPin_SingleRailroad_SwitchRailroads()
        {
            // Arrange
            var WSORHartfordBeacon = TestData.WSOR_Hartford_WI(_currentDateTime);
            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = 23424,
                Source = "HOT",
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime
            };

            // Train just got on CN from WSOR
            var beaconRailroads = new List<BeaconRailroad>
            {
                CNRugbyJunctionBeacon
            };

            var previousMapPin = new MapPin
            {
                ID = 29032,
                BeaconID = WSORHartfordBeacon.BeaconID,
                SubdivisionId = WSORHartfordBeacon.Subdivision.ID,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = WSORHartfordBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = telemetry.Source,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var expectedMapPinBeforeInsert = new MapPin
            {
                ID = previousMapPin.ID, // Reuse previous map pin ID to avoid duplicates on map.
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                Direction = "S",
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = telemetry.Source,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var expectedMapPinAfterInsert = expectedMapPinBeforeInsert.Clone();
            expectedMapPinAfterInsert.ID = 234;

            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = expectedMapPinAfterInsert.ID,
                    Direction = "S",
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNRugbyJunctionBeacon.Beacon.Name,
                    Railroad = CNRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = CNRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = CNRugbyJunctionBeacon.Latitude,
                    Longitude = CNRugbyJunctionBeacon.Longitude,
                    Milepost = CNRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = telemetry.AddressID,
                            Source = telemetry.Source
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(previousMapPin);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNRugbyJunctionBeacon.SubdivisionID, 5))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(expectedMapPinBeforeInsert))
                .ReturnsAsync(expectedMapPinAfterInsert);

            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(previousMapPin.BeaconID, previousMapPin.SubdivisionId))
                .ReturnsAsync(WSORHartfordBeacon); // Not the same beacon as new telemetry.

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(expectedMapPinBeforeInsert), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Once);
        }

        /// <summary>
        /// If a train emitting HOT telemetry from a single track and later detected emitting EOT telemetry by a 
        /// multi-track beacon, multi-railroad, the existing map pin should be updated with the additional source
        /// for the HOT with a calculated direction.
        /// </summary>
        [TestMethod]
        public async Task UpsertMapPin_SingleRailroad_SameAddress_DifferentSource()
        {
            // Arrange
            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);
            var WSORRugbyJunctionBeacon = TestData.WSOR_RugbyJunction_WI(_currentDateTime);

            var fromDirection = null as string;
            var fromSource = "HOT";

            var toDirection = "N";
            var toSource = "EOT";

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = 23424,
                Source = toSource,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime
            };

            var fromBeaconRailroads = new List<BeaconRailroad>
            {
                CNSussexBeacon
            };

            var toBeaconRailroads = new List<BeaconRailroad>
            {
                CNRugbyJunctionBeacon,
                WSORRugbyJunctionBeacon
            };

            var fromMapPin = new MapPin
            {
                ID = 234,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = fromDirection,
                CreatedAt = _currentDateTime.AddSeconds(-5),
                LastUpdate = _currentDateTime.AddSeconds(-5),
                BeaconRailroad = CNSussexBeacon,
                Moving = telemetry.Moving,
                Addresses =
                    [
                        new Address
                        {
                            AddressID = telemetry.AddressID,
                            Source = fromSource, // Different source from new telemetry (HOT > EOT)
                            CreatedAt = _currentDateTime.AddSeconds(-5),
                            LastUpdate = _currentDateTime.AddSeconds(-5)
                        }
                    ],
            };

            var toMapPinBeforeUpdate = new MapPin
            {
                ID = fromMapPin.ID,
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                Direction = toDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = fromSource,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    },
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = toSource,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var toMapPinAfterUpdate = toMapPinBeforeUpdate.Clone();
            toMapPinAfterUpdate.ID = 345; // New ID after insert.

            var toMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = toMapPinAfterUpdate.ID,
                    Direction = toDirection,
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNRugbyJunctionBeacon.Beacon.Name,
                    Railroad = CNRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = CNRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = CNRugbyJunctionBeacon.Latitude,
                    Longitude = CNRugbyJunctionBeacon.Longitude,
                    Milepost = CNRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = telemetry.AddressID,
                            Source = fromSource
                        },
                        new AddressDTO
                        {
                            AddressID = telemetry.AddressID,
                            Source = toSource
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(fromMapPin); // Simulate previous map pin exists.
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNSussexBeacon.SubdivisionID, 5))
                .ReturnsAsync((MapPin?)null);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(fromMapPin.BeaconID, fromMapPin.SubdivisionId))
                .ReturnsAsync(fromBeaconRailroads[0]); // Not the same beacon as new telemetry.
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(It.IsAny<MapPin>()))
                .ReturnsAsync(toMapPinAfterUpdate);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, It.IsAny<object[]>(), default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, toBeaconRailroads);

            // Assert - only EOT should be added (no automatic HOT pairing)
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(It.Is<MapPin>(mp =>
                mp.Addresses.Count == 2 &&
                mp.Addresses.Any(a => a.Source == fromSource && a.AddressID == telemetry.AddressID) &&
                mp.Addresses.Any(a => a.Source == toSource && a.AddressID == telemetry.AddressID)
            )), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => 
                    args.Length > 0 && 
                    args[0] != null &&
                    ((MapPinDTO)args[0]).Addresses.Count == 2 &&
                    ((MapPinDTO)args[0]).Addresses.Any(a => a.Source == fromSource) &&
                    ((MapPinDTO)args[0]).Addresses.Any(a => a.Source == toSource)
                ),
                default), Times.Once);
        }

        /// <summary>
        /// If a train emitting HOT telemetry from a single track and later detected emitting HOT telemetry by a 
        /// multi-track beacon, multi-railroad, the existing map pin last update should be updated.
        /// </summary>
        [TestMethod]
        public async Task UpsertMapPin_SingleRailroad_SameAddress_SameSource()
        {
            // Arrange
            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var WSORRugbyJunctionBeacon = TestData.WSOR_RugbyJunction_WI(_currentDateTime);
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);

            var toDirection = "N";

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = 23424,
                Source = "HOT",
                Moving = true,
                CreatedAt = _currentDateTime.AddMinutes(1),
                LastUpdate = _currentDateTime.AddMinutes(2)
            };

            var fromBeaconRailroads = new List<BeaconRailroad>
            {
                CNSussexBeacon
            };

            var toBeaconRailroads = new List<BeaconRailroad>
            {
                CNRugbyJunctionBeacon,
                WSORRugbyJunctionBeacon
            };

            var fromMapPin = new MapPin
            {
                ID = 234,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNSussexBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = telemetry.Source, // Same source as new telemetry (HOT > HOT)
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var toMapPinBeforeUpdate = new MapPin
            {
                ID = fromMapPin.ID,
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                Direction = toDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = telemetry.LastUpdate,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = telemetry.Source,
                        CreatedAt = _currentDateTime,
                        LastUpdate = telemetry.LastUpdate
                    }
                ],
            };

            var toMapPinAfterUpdate = toMapPinBeforeUpdate;

            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = toMapPinAfterUpdate.ID,
                    Direction = toDirection,
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNRugbyJunctionBeacon.Beacon.Name,
                    Railroad = CNRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = CNRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = CNRugbyJunctionBeacon.Latitude,
                    Longitude = CNRugbyJunctionBeacon.Longitude,
                    Milepost = CNRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = telemetry.LastUpdate,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = telemetry.AddressID,
                            Source = telemetry.Source
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(fromMapPin); // Simulate previous map pin exists.
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNSussexBeacon.SubdivisionID, 5))
                .ReturnsAsync((MapPin?)null);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(fromMapPin.BeaconID, fromMapPin.SubdivisionId))
                .ReturnsAsync(fromBeaconRailroads[0]); // Not the same beacon as new telemetry.
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(toMapPinBeforeUpdate))
                .ReturnsAsync(toMapPinAfterUpdate);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, toBeaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(toMapPinBeforeUpdate), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Once);
        }

        [TestMethod]
        public async Task UpsertMapPin_UpdateMapPin_SingleRailroad_SameAddress_LateEotAfterHot()
        {
            // Arrange
            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);

            var calculatedDirection = null as string; // Can't calculate direction on multi-track, multi-railroad beacon.

            var newSource = "EOT";
            var previousSource = "HOT";

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = 23424,
                Source = newSource,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime
            };

            var toBeaconRailroads = new List<BeaconRailroad>
            {
                CNRugbyJunctionBeacon
            };

            var fromBeaconRailroads = new List<BeaconRailroad>
            {
                CNSussexBeacon
            };

            var previousMapPin = new MapPin
            {
                ID = 234,
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                    [
                        new Address
                        {
                            AddressID = telemetry.AddressID,
                            Source = previousSource,
                            CreatedAt = _currentDateTime.AddMinutes(-1), // Older than new telemetry.
                            LastUpdate = _currentDateTime.AddMinutes(-1)
                        }
                    ],
            };

            var toMapPinBeforeUpdate = new MapPin
            {
                ID = previousMapPin.ID, // Keep the same ID to update the existing map pin.
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                Direction = calculatedDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = previousSource,
                        CreatedAt = _currentDateTime.AddMinutes(-1),
                        LastUpdate = telemetry.LastUpdate
                    },
                    new Address
                    {
                        AddressID = telemetry.AddressID,
                        Source = newSource,
                        CreatedAt = telemetry.CreatedAt,
                        LastUpdate = telemetry.LastUpdate
                    }
                ],
            };

            var toMapPinAfterUpdate = toMapPinBeforeUpdate.Clone();

            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = previousMapPin.ID,
                    Direction = calculatedDirection,
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNRugbyJunctionBeacon.Beacon.Name,
                    Railroad = CNRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = CNRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = CNRugbyJunctionBeacon.Latitude,
                    Longitude = CNRugbyJunctionBeacon.Longitude,
                    Milepost = CNRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = telemetry.AddressID,
                            Source = previousSource
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(previousMapPin);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNSussexBeacon.SubdivisionID, 5))
                .ReturnsAsync((MapPin?)null);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(previousMapPin.BeaconID, previousMapPin.SubdivisionId))
                .ReturnsAsync(fromBeaconRailroads[0]);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(toMapPinBeforeUpdate))
                .ReturnsAsync(toMapPinAfterUpdate);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, toBeaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(toMapPinBeforeUpdate), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Never);
        }

        /// <summary>
        /// If a train emitting HOT telemetry from a single track and later detected emitting DPU telemetry by the
        /// same single-track beacon, the existing map pin should be updated with the additional source
        /// for the DPU.
        /// </summary>
        [TestMethod]
        public async Task UpsertMapPin_SingleRailroad_TimeThreshold_PreviousDirection()
        {
            // Arrange
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);

            var fromAddressID = 92342;
            var fromDirection = "N";
            var fromSource = "HOT";

            var toAddressID = 23424;
            var toDirection = "N";
            var toSource = "DPU";

            var telemetry = new Telemetry
            {
                BeaconID = CNSussexBeacon.BeaconID,
                AddressID = toAddressID,
                Source = toSource,
                Moving = true,
                CreatedAt = _currentDateTime.AddMinutes(1),
                LastUpdate = _currentDateTime.AddMinutes(2)
            };

            var beaconRailroads = new List<BeaconRailroad>
            {
                CNSussexBeacon
            };

            var fromMapPin = new MapPin
            {
                ID = 234,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = fromDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = telemetry.LastUpdate,
                BeaconRailroad = CNSussexBeacon,
                Moving = telemetry.Moving,
                Addresses =
                    [
                        new Address
                        {
                            AddressID = fromAddressID,
                            Source = fromSource,
                            CreatedAt = _currentDateTime,
                            LastUpdate = _currentDateTime
                        }
                    ],
            };

            var toMapPinBeforeUpdate = new MapPin
            {
                ID = 234,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = toDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = telemetry.LastUpdate,
                BeaconRailroad = CNSussexBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = fromAddressID,
                        Source = fromSource,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    },
                    new Address
                    {
                        AddressID = toAddressID,
                        Source = toSource,
                        CreatedAt = telemetry.CreatedAt,
                        LastUpdate = telemetry.LastUpdate,
                    }
                ],
            };

            var toMapPinAfterUpdate = toMapPinBeforeUpdate;

            var toMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = toMapPinBeforeUpdate.ID,
                    Direction = toDirection,
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNSussexBeacon.Beacon.Name,
                    Railroad = CNSussexBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNSussexBeacon.Subdivision.Name,
                    SubdivisionID = CNSussexBeacon.Subdivision.ID,
                    Latitude = CNSussexBeacon.Latitude,
                    Longitude = CNSussexBeacon.Longitude,
                    Milepost = CNSussexBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = telemetry.LastUpdate,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = fromAddressID,
                            Source = fromSource
                        },
                        new AddressDTO
                        {
                            AddressID = toAddressID,
                            Source = toSource
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNSussexBeacon.SubdivisionID, MapPinService.TIME_THRESHOLD_MINUTES))
                .ReturnsAsync(fromMapPin);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(fromMapPin.BeaconID, fromMapPin.SubdivisionId))
                .ReturnsAsync(beaconRailroads[0]);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(toMapPinBeforeUpdate))
                .ReturnsAsync(toMapPinAfterUpdate);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, toMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(toMapPinBeforeUpdate), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(toMapPinObjects[0])),
                default), Times.Once);
        }

        [TestMethod]
        public async Task UpsertMapPin_UpdateMapPin_SingleRailroad_MultiTrack_PreviousDirection()
        {
            // Arrange
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);
            CNSussexBeacon.MultipleTracks = true; // Enable multi-track for this test.

            var calculatedDirection = "N";

            var newSource = "DPU";
            var previousSource = "HOT";

            var newAddressID = 23424;
            var previousAddressID = 92342;

            var telemetry = new Telemetry
            {
                BeaconID = CNSussexBeacon.BeaconID,
                AddressID = newAddressID,
                Source = newSource,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime
            };

            var beaconRailroads = new List<BeaconRailroad>
            {
                CNSussexBeacon
            };

            var previousMapPin = new MapPin
            {
                ID = 234,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = calculatedDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNSussexBeacon,
                Moving = telemetry.Moving,
                Addresses =
                    [
                        new Address
                        {
                            AddressID = previousAddressID,
                            Source = previousSource,
                            CreatedAt = _currentDateTime,
                            LastUpdate = _currentDateTime
                        }
                    ],
            };

            var expectedMapPinBeforeUpdate = new MapPin
            {
                ID = 0, // New map pin won't have an yet ID
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = null, // Can't calculate direction
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNSussexBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = newAddressID,
                        Source = newSource,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var expectedMapPinAfterUpdate = expectedMapPinBeforeUpdate.Clone();
            expectedMapPinAfterUpdate.ID = 234; // ID returned after insert.

            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = 234,
                    Direction = null,
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNSussexBeacon.Beacon.Name,
                    Railroad = CNSussexBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNSussexBeacon.Subdivision.Name,
                    SubdivisionID = CNSussexBeacon.Subdivision.ID,
                    Latitude = CNSussexBeacon.Latitude,
                    Longitude = CNSussexBeacon.Longitude,
                    Milepost = CNSussexBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = newAddressID,
                            Source = newSource
                        }
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNSussexBeacon.SubdivisionID, MapPinService.TIME_THRESHOLD_MINUTES))
                .ReturnsAsync(previousMapPin);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(previousMapPin.BeaconID, previousMapPin.SubdivisionId))
                .ReturnsAsync(beaconRailroads[0]);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(expectedMapPinBeforeUpdate))
                .ReturnsAsync(expectedMapPinAfterUpdate);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(expectedMapPinBeforeUpdate), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Once);
        }

        /// <summary>
        /// Summary:
        /// If a train emitting HOT telemetry from a single track and later detected emitting DPU telemetry by a 
        /// multi-track beacon, a new map pin should be created for the DPU address with no direction.
        /// 
        /// Due to the multi-track nature of the beacon, there is no way to determine which train the DPU is on
        /// and therefore no direction can be calculated.
        /// 
        /// If:
        /// - Both beacons are on the same railroad
        /// - Railroad is DPU capable 
        /// - From beacon is single track
        /// - To beacon railroad is multi track
        /// - To beacon detects telemetry from DPU source
        /// - From beacon map pin exists within time threshold
        /// Then:
        /// - Create new DPU map pin for to beacon with no direction
        /// </summary>
        [TestMethod]
        public async Task UpsertMapPin_SingleRailroad_SingleToMultiTrack_DifferentAddress_DpuSource()
        {
            // Arrange
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);
            var fromDirection = null as String;
            var fromAddressID = 92342;
            var fromSource = "HOT";

            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var toDirection = null as String;
            var toAddressID = 23424;
            var toSource = "DPU";

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = toAddressID,
                Source = toSource,
                Moving = true,
                CreatedAt = _currentDateTime.AddMinutes(2), // Later than previous map pin, but still in time threshold.
                LastUpdate = _currentDateTime.AddMinutes(2),
            };

            var beaconRailroads = new List<BeaconRailroad>
            {
                CNRugbyJunctionBeacon,
                CNSussexBeacon
            };

            var fromMapPin = new MapPin
            {
                ID = 234,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = fromDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNSussexBeacon,
                Moving = telemetry.Moving,
                Addresses =
                    [
                        new Address
                        {
                            AddressID = fromAddressID,
                            Source = fromSource,
                            CreatedAt = _currentDateTime,
                            LastUpdate = _currentDateTime
                        }
                    ],
            };

            var toMapPinBeforeUpdate = new MapPin
            {
                ID = 0, // New map pin won't have an yet ID
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                Direction = null, // Can't calculate direction for DPU
                CreatedAt = telemetry.CreatedAt,
                LastUpdate = telemetry.LastUpdate,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = toAddressID,
                        Source = toSource,
                        CreatedAt = telemetry.CreatedAt,
                        LastUpdate = telemetry.LastUpdate
                    }
                ],
            };

            var toMapPinAfterUpdate = toMapPinBeforeUpdate.Clone();
            toMapPinAfterUpdate.ID = 936; // ID returned after insert.

            var toMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = toMapPinAfterUpdate.ID,
                    Direction = toDirection,
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNRugbyJunctionBeacon.Beacon.Name,
                    Railroad = CNRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = CNRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = CNRugbyJunctionBeacon.Latitude,
                    Longitude = CNRugbyJunctionBeacon.Longitude,
                    Milepost = CNRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = telemetry.CreatedAt,
                    LastUpdate = telemetry.LastUpdate,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = toAddressID,
                            Source = toSource
                        }
                    ],
                }
             };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNSussexBeacon.Subdivision.RailroadID, 5))
                .ReturnsAsync(fromMapPin);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(fromMapPin.BeaconID, fromMapPin.SubdivisionId))
                .ReturnsAsync(beaconRailroads[0]);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(toMapPinBeforeUpdate))
                .ReturnsAsync(toMapPinAfterUpdate);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, toMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(toMapPinBeforeUpdate), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(toMapPinObjects[0])),
                default), Times.Once);
        }

        [TestMethod]
        public async Task UpsertMapPin_UpdateMapPin_SingleDpuCapableRailroad_TimeThreshold_PreviousHOTandEOT()
        {
            // Arrange
            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);
            var WSORRugbyJunctionBeacon = TestData.WSOR_RugbyJunction_WI(_currentDateTime);

            var calculatedDirection = "N";

            var newDpuSource = "DPU";
            var previousHotSource1 = "HOT";
            var previousEotSource2 = "EOT";

            var newAddressID = 46969;
            var previousAddressID1 = 32591;
            var previousAddressID2 = 32591;

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = newAddressID,
                Source = newDpuSource,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime
            };

            var beaconRailroads = new List<BeaconRailroad>
            {
                CNRugbyJunctionBeacon,
                WSORRugbyJunctionBeacon
            };

            var previousMapPin = new MapPin
            {
                ID = 0,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = calculatedDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNSussexBeacon,
                Moving = null,
                Addresses =
                    [
                        new Address
                        {
                            AddressID = previousAddressID1,
                            Source = previousHotSource1,
                            CreatedAt = _currentDateTime.AddMinutes(-2),
                            LastUpdate = _currentDateTime.AddMinutes(-2)
                        },
                        new Address
                        {
                            AddressID = previousAddressID2,
                            Source = previousEotSource2,
                            CreatedAt = _currentDateTime.AddMinutes(-1),
                            LastUpdate = _currentDateTime.AddMinutes(-1)
                        }
                    ],
            };

            var expectedMapPinBeforeInsert = new MapPin
            {
                ID = 0, // ID will be set by InsertAsync.
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                Direction = null, // Can't predict direction because DPU group logic doesn't exist yet.
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = newAddressID,
                        Source = newDpuSource,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var expectedMapPinAfterInsert = expectedMapPinBeforeInsert;

            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = expectedMapPinBeforeInsert.ID,
                    Direction = null, // Can't predict direction because DPU group logic doesn't exist yet.
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNRugbyJunctionBeacon.Beacon.Name,
                    Railroad = CNRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = CNRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = CNRugbyJunctionBeacon.Latitude,
                    Longitude = CNRugbyJunctionBeacon.Longitude,
                    Milepost = CNRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = newAddressID,
                            Source = newDpuSource
                        },
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNRugbyJunctionBeacon.SubdivisionID, 5))
                .ReturnsAsync(previousMapPin);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(previousMapPin.BeaconID, previousMapPin.SubdivisionId))
                .ReturnsAsync(beaconRailroads[0]);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(expectedMapPinBeforeInsert))
                .ReturnsAsync(expectedMapPinAfterInsert);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(expectedMapPinBeforeInsert), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Once);
        }

        [TestMethod]
        public async Task UpsertMapPin_UpdateMapPin_SingleDpuCapableRailroad_TimeThreshold_PreviousDPU()
        {
            // Arrange
            var CNRugbyJunctionBeacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var CNSussexBeacon = TestData.CN_Sussex_WI(_currentDateTime);
            var WSORRugbyJunctionBeacon = TestData.WSOR_RugbyJunction_WI(_currentDateTime);

            var calculatedDirection = "N";

            var newDpuSource = "HOT";
            var previousHotSource1 = "DPU";

            var newAddressID = 46969;
            var previousAddressID1 = 32591;

            var telemetry = new Telemetry
            {
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                AddressID = newAddressID,
                Source = newDpuSource,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime
            };

            var beaconRailroads = new List<BeaconRailroad>
            {
                CNRugbyJunctionBeacon,
                WSORRugbyJunctionBeacon
            };

            var previousMapPin = new MapPin
            {
                ID = 0,
                BeaconID = CNSussexBeacon.BeaconID,
                SubdivisionId = CNSussexBeacon.Subdivision.ID,
                Direction = calculatedDirection,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNSussexBeacon,
                Moving = null,
                Addresses =
                    [
                        new Address
                        {
                            AddressID = previousAddressID1,
                            Source = previousHotSource1,
                            CreatedAt = _currentDateTime.AddMinutes(-2),
                            LastUpdate = _currentDateTime.AddMinutes(-2)
                        }
                    ],
            };

            var expectedMapPinBeforeInsert = new MapPin
            {
                ID = 0, // ID will be set by InsertAsync.
                BeaconID = CNRugbyJunctionBeacon.BeaconID,
                SubdivisionId = CNRugbyJunctionBeacon.Subdivision.ID,
                Direction = null, // Can't predict direction because DPU group logic doesn't exist yet.
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime,
                BeaconRailroad = CNRugbyJunctionBeacon,
                Moving = telemetry.Moving,
                Addresses =
                [
                    new Address
                    {
                        AddressID = newAddressID,
                        Source = newDpuSource,
                        CreatedAt = _currentDateTime,
                        LastUpdate = _currentDateTime
                    }
                ],
            };

            var expectedMapPinAfterInsert = expectedMapPinBeforeInsert;

            var expectedMapPinObjects = new object[]
            {
                new MapPinDTO
                {
                    ID = expectedMapPinBeforeInsert.ID,
                    Direction = null, // Can't predict direction because DPU group logic doesn't exist yet.
                    BeaconID = telemetry.BeaconID,
                    BeaconName = CNRugbyJunctionBeacon.Beacon.Name,
                    Railroad = CNRugbyJunctionBeacon.Subdivision.Railroad.Name,
                    Subdivision = CNRugbyJunctionBeacon.Subdivision.Name,
                    SubdivisionID = CNRugbyJunctionBeacon.Subdivision.ID,
                    Latitude = CNRugbyJunctionBeacon.Latitude,
                    Longitude = CNRugbyJunctionBeacon.Longitude,
                    Milepost = CNRugbyJunctionBeacon.Milepost,
                    Moving = telemetry.Moving,
                    CreatedAt = _currentDateTime,
                    LastUpdate = _currentDateTime,
                    Addresses =
                    [
                        new AddressDTO
                        {
                            AddressID = newAddressID,
                            Source = newDpuSource
                        },
                    ],
                }
            };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync((MapPin?)null);
            _mapPinRepositoryMock.Setup(r => r.GetByTimeThreshold(telemetry.BeaconID, CNRugbyJunctionBeacon.SubdivisionID, 5))
                .ReturnsAsync(previousMapPin);
            _beaconRailroadServiceMock.Setup(s => s.GetByIdAsync(previousMapPin.BeaconID, previousMapPin.SubdivisionId))
                .ReturnsAsync(beaconRailroads[0]);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(expectedMapPinBeforeInsert))
                .ReturnsAsync(expectedMapPinAfterInsert);

            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate, expectedMapPinObjects, default))
                    .Returns(Task.CompletedTask);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(expectedMapPinBeforeInsert), Times.Once);

            _clientProxyMock?.Verify(proxy => proxy.SendCoreAsync(
                NotificationMethods.MapPinUpdate,
                It.Is<object[]>(args => args[0].Equals(expectedMapPinObjects[0])),
                default), Times.Once);
        }

        /// <summary>
        /// Test that when DPU telemetry arrives with new address, it's added to the map pin.
        /// </summary>
        [TestMethod]
        public async Task UpdateMapPin_DPU_NewAddress_OnlyDPUAdded()
        {
            // Arrange
            var beacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var telemetry = new Telemetry
            {
                BeaconID = beacon.BeaconID,
                AddressID = 54321,
                TrainID = 9999,
                Source = SourceEnum.DPU,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime.AddMinutes(1)
            };

            var previousMapPin = new MapPin
            {
                ID = 100,
                BeaconID = beacon.BeaconID,
                SubdivisionId = beacon.Subdivision.ID,
                Direction = "N",
                CreatedAt = _currentDateTime.AddMinutes(-10),
                LastUpdate = _currentDateTime,
                BeaconRailroad = beacon,
                Moving = true,
                Addresses =
                [
                    new Address { AddressID = 12345, Source = SourceEnum.HOT, CreatedAt = _currentDateTime.AddMinutes(-10), LastUpdate = _currentDateTime }
                ]
            };

            var beaconRailroads = new List<BeaconRailroad> { beacon };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(previousMapPin);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(It.IsAny<MapPin>()))
                .ReturnsAsync((MapPin mp) => mp);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);
            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(It.IsAny<string>(), It.IsAny<object[]>(), default))
                .Returns(Task.CompletedTask);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert - should have 2 addresses: original HOT + new DPU
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(It.Is<MapPin>(mp =>
                mp.Addresses.Count == 2 &&
                mp.Addresses.Any(a => a.Source == SourceEnum.HOT && a.AddressID == 12345) &&
                mp.Addresses.Any(a => a.Source == SourceEnum.DPU && a.AddressID == 54321)
            )), Times.Once);
        }

        /// <summary>
        /// Test that when telemetry arrives with same address and source (timestamp update only), no new address is added.
        /// </summary>
        [TestMethod]
        public async Task UpdateMapPin_SameAddressAndSource_TimestampUpdateOnly()
        {
            // Arrange
            var beacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var telemetry = new Telemetry
            {
                BeaconID = beacon.BeaconID,
                AddressID = 12345,
                Source = SourceEnum.HOT,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime.AddMinutes(5)
            };

            var previousMapPin = new MapPin
            {
                ID = 100,
                BeaconID = beacon.BeaconID,
                SubdivisionId = beacon.Subdivision.ID,
                Direction = "N",
                CreatedAt = _currentDateTime.AddMinutes(-10),
                LastUpdate = _currentDateTime,
                BeaconRailroad = beacon,
                Moving = true,
                Addresses =
                [
                    new Address { AddressID = 12345, Source = SourceEnum.HOT, CreatedAt = _currentDateTime.AddMinutes(-10), LastUpdate = _currentDateTime }
                ]
            };

            var beaconRailroads = new List<BeaconRailroad> { beacon };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(previousMapPin);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(It.IsAny<MapPin>()))
                .ReturnsAsync((MapPin mp) => mp);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);
            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(It.IsAny<string>(), It.IsAny<object[]>(), default))
                .Returns(Task.CompletedTask);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert - should still have exactly 1 address with updated timestamp
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(It.Is<MapPin>(mp =>
                mp.Addresses.Count == 1 &&
                mp.Addresses.First().AddressID == 12345 &&
                mp.Addresses.First().Source == SourceEnum.HOT &&
                mp.LastUpdate == telemetry.LastUpdate
            )), Times.Once);
        }

        /// <summary>
        /// Test that when telemetry arrives at same beacon within threshold time, direction is preserved.
        /// </summary>
        [TestMethod]
        public async Task UpdateMapPin_SameBeacon_WithinThreshold_DirectionPreserved()
        {
            // Arrange
            var beacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var telemetry = new Telemetry
            {
                BeaconID = beacon.BeaconID,
                AddressID = 12345,
                Source = SourceEnum.HOT,
                Moving = true,
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime.AddMinutes(5) // Only 5 minutes after creation
            };

            var previousMapPin = new MapPin
            {
                ID = 100,
                BeaconID = beacon.BeaconID,
                SubdivisionId = beacon.Subdivision.ID,
                Direction = "N", // Should be preserved
                CreatedAt = _currentDateTime, // Just created
                LastUpdate = _currentDateTime,
                BeaconRailroad = beacon,
                Moving = true,
                Addresses =
                [
                    new Address { AddressID = 12345, Source = SourceEnum.HOT, CreatedAt = _currentDateTime, LastUpdate = _currentDateTime }
                ]
            };

            var beaconRailroads = new List<BeaconRailroad> { beacon };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(previousMapPin);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(It.IsAny<MapPin>()))
                .ReturnsAsync((MapPin mp) => mp);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);
            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(It.IsAny<string>(), It.IsAny<object[]>(), default))
                .Returns(Task.CompletedTask);

            // Setup time to be 5 minutes after creation (under 360 minute threshold)
            _timeProviderMock.Setup(tp => tp.UtcNow).Returns(_currentDateTime.AddMinutes(5));

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert - direction should still be "N"
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(It.Is<MapPin>(mp =>
                mp.Direction == "N"
            )), Times.Once);
        }

        /// <summary>
        /// Test that when telemetry has no Moving value, map pin Moving is not updated.
        /// </summary>
        [TestMethod]
        public async Task UpdateMapPin_NoMovingValue_MovingNotUpdated()
        {
            // Arrange
            var beacon = TestData.CN_RugbyJunction_WI(_currentDateTime);
            var telemetry = new Telemetry
            {
                BeaconID = beacon.BeaconID,
                AddressID = 12345,
                Source = SourceEnum.HOT,
                Moving = null, // No moving value
                CreatedAt = _currentDateTime,
                LastUpdate = _currentDateTime.AddMinutes(1)
            };

            var previousMapPin = new MapPin
            {
                ID = 100,
                BeaconID = beacon.BeaconID,
                SubdivisionId = beacon.Subdivision.ID,
                Direction = "N",
                CreatedAt = _currentDateTime.AddMinutes(-10),
                LastUpdate = _currentDateTime,
                BeaconRailroad = beacon,
                Moving = true, // Should remain true
                Addresses =
                [
                    new Address { AddressID = 12345, Source = SourceEnum.HOT, CreatedAt = _currentDateTime.AddMinutes(-10), LastUpdate = _currentDateTime }
                ]
            };

            var beaconRailroads = new List<BeaconRailroad> { beacon };

            _mapPinRepositoryMock.Setup(r => r.GetByAddressIdAsync(telemetry.AddressID))
                .ReturnsAsync(previousMapPin);
            _mapPinRepositoryMock.Setup(r => r.UpsertAsync(It.IsAny<MapPin>()))
                .ReturnsAsync((MapPin mp) => mp);
            _hubContextMock.Setup(h => h.Clients).Returns(_hubClientsMock.Object);
            _hubClientsMock.Setup(h => h.All).Returns(_clientProxyMock.Object);
            _clientProxyMock.Setup(proxy => proxy.SendCoreAsync(It.IsAny<string>(), It.IsAny<object[]>(), default))
                .Returns(Task.CompletedTask);

            // Act
            await _service.UpsertMapPin(telemetry, beaconRailroads);

            // Assert - Moving should still be true (not updated to null)
            _mapPinRepositoryMock.Verify(r => r.UpsertAsync(It.Is<MapPin>(mp =>
                mp.Moving == true
            )), Times.Once);
        }

        private static class TestData
        {
            public static Beacon Hartford_WI()
            {
                return new Beacon
                {
                    ID = 4,
                    OwnerID = 1,
                    Name = "Hartford",
                    CreatedAt = DateTime.UtcNow,
                    LastUpdate = DateTime.UtcNow
                };
            }

            public static Beacon RugbyJunction_WI()
            {
                return new Beacon
                {
                    ID = 1,
                    OwnerID = 1,
                    Name = "Rugby Junction",
                    CreatedAt = DateTime.UtcNow,
                    LastUpdate = DateTime.UtcNow
                };
            }

            public static Beacon Sussex_WI()
            {
                return new Beacon
                {
                    ID = 2,
                    OwnerID = 1,
                    Name = "Sussex",
                    CreatedAt = DateTime.UtcNow,
                    LastUpdate = DateTime.UtcNow
                };
            }


            public static BeaconRailroad CN_RugbyJunction_WI(DateTime currentDateTime)
            {
                return new BeaconRailroad
                {
                    BeaconID = 1,
                    Beacon = TestData.RugbyJunction_WI(),
                    SubdivisionID = 1,
                    Subdivision = TestData.CN_Waukesha(currentDateTime),
                    Direction = Direction.NorthSouth,
                    Latitude = 43.280958,
                    Longitude = -88.214682,
                    Milepost = 117.2,
                    MultipleTracks = true,
                    CreatedAt = currentDateTime,
                    LastUpdate = currentDateTime
                };
            }

            public static BeaconRailroad CN_Sussex_WI(DateTime currentDateTime)
            {
                return new BeaconRailroad
                {
                    BeaconID = 2,
                    Beacon = TestData.Sussex_WI(),
                    SubdivisionID = 1,
                    Subdivision = TestData.CN_Waukesha(currentDateTime),
                    Direction = Direction.NorthSouth,
                    Latitude = 43.159517,
                    Longitude = -88.200492,
                    Milepost = 108.6,
                    MultipleTracks = false,
                    CreatedAt = currentDateTime,
                    LastUpdate = currentDateTime
                };
            }

            public static BeaconRailroad WSOR_RugbyJunction_WI(DateTime currentDateTime)
            {
                return new BeaconRailroad
                {
                    BeaconID = 3,
                    Beacon = TestData.RugbyJunction_WI(),
                    SubdivisionID = 2,
                    Subdivision = TestData.WSOR_Milwaukee(currentDateTime),
                    Direction = Direction.NorthwestSoutheast,
                    Latitude = 43.280958,
                    Longitude = -88.213966,
                    Milepost = 112.16,
                    MultipleTracks = false,
                    CreatedAt = currentDateTime,
                    LastUpdate = currentDateTime
                };
            }

            public static BeaconRailroad WSOR_Hartford_WI(DateTime currentDateTime)
            {
                return new BeaconRailroad
                {
                    BeaconID = 4,
                    Beacon = TestData.Hartford_WI(),
                    SubdivisionID = 2,
                    Subdivision = TestData.WSOR_Milwaukee(currentDateTime),
                    Direction = Direction.NorthwestSoutheast,
                    Latitude = 43.319359,
                    Longitude = -88.367589,
                    Milepost = 121,
                    MultipleTracks = false,
                    CreatedAt = currentDateTime,
                    LastUpdate = currentDateTime
                };
            }

            public static Subdivision CN_Waukesha(DateTime currentDateTime)
            {
                return
                        new Subdivision
                        {
                            ID = 1,
                            Name = "Waukesha",
                            RailroadID = 1,
                            Railroad = new Railroad { ID = 1, Name = "CN" },
                            DpuCapable = true,
                            CreatedAt = currentDateTime,
                            LastUpdate = currentDateTime
                        };
            }

            public static Subdivision WSOR_Milwaukee(DateTime currentDateTime)
            {
                return new Subdivision
                {
                    ID = 2,
                    Name = "Milwaukee",
                    RailroadID = 2,
                    Railroad = new Railroad { ID = 2, Name = "WSOR" },
                    DpuCapable = false,
                    CreatedAt = currentDateTime,
                    LastUpdate = currentDateTime
                };
            }

            public static Subdivision WSOR_Horicon(DateTime currentDateTime)
            {
                return new Subdivision
                {
                    ID = 5,
                    Name = "Horicon",
                    RailroadID = 2,
                    Railroad = new Railroad { ID = 2, Name = "WSOR" },
                    DpuCapable = false,
                    CreatedAt = currentDateTime,
                    LastUpdate = currentDateTime
                };
            }
        }
    }
}