// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Server.Data;

#nullable disable

namespace Web.Server.Migrations
{
    [DbContext(typeof(Data.TelemetryDbContext))]
    [Migration("20250503223704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("Web.Server.Entities.Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Web.Server.Entities.Railroad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subdivision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("BeaconID");

                    b.ToTable("Railroads");
                });

            modelBuilder.Entity("Web.Server.Entities.Telemetry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Moving")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BeaconID");

                    b.ToTable("Telemetries");
                });

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.HasOne("Web.Server.Entities.Owner", null)
                        .WithMany("Beacons")
                        .HasForeignKey("OwnerID");
                });

            modelBuilder.Entity("Web.Server.Entities.Railroad", b =>
                {
                    b.HasOne("Web.Server.Entities.Beacon", null)
                        .WithMany("Railroads")
                        .HasForeignKey("BeaconID");
                });

            modelBuilder.Entity("Web.Server.Entities.Telemetry", b =>
                {
                    b.HasOne("Web.Server.Entities.Beacon", "Beacon")
                        .WithMany()
                        .HasForeignKey("BeaconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.Navigation("Railroads");
                });

            modelBuilder.Entity("Web.Server.Entities.Owner", b =>
                {
                    b.Navigation("Beacons");
                });
#pragma warning restore 612, 618
        }
    }
}
