// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Server.Data;

#nullable disable

namespace Web.Server.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20250507223832_EnabledSoftDelete")]
    partial class EnabledSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("Web.Server.Entities.BeaconRailroad", b =>
                {
                    b.Property<int>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RailroadID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("BeaconID", "RailroadID");

                    b.HasIndex("RailroadID");

                    b.ToTable("BeaconRailroads");
                });

            modelBuilder.Entity("Web.Server.Entities.Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Web.Server.Entities.Railroad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subdivision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Railroads");
                });

            modelBuilder.Entity("Web.Server.Entities.Telemetry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Moving")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BeaconID");

                    b.ToTable("Telemetries");
                });

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.HasOne("Web.Server.Entities.Owner", "Owner")
                        .WithMany("Beacons")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Web.Server.Entities.BeaconRailroad", b =>
                {
                    b.HasOne("Web.Server.Entities.Beacon", "Beacon")
                        .WithMany("BeaconRailroads")
                        .HasForeignKey("BeaconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Server.Entities.Railroad", "Railroad")
                        .WithMany("BeaconRailroads")
                        .HasForeignKey("RailroadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");

                    b.Navigation("Railroad");
                });

            modelBuilder.Entity("Web.Server.Entities.Telemetry", b =>
                {
                    b.HasOne("Web.Server.Entities.Beacon", "Beacon")
                        .WithMany()
                        .HasForeignKey("BeaconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.Navigation("BeaconRailroads");
                });

            modelBuilder.Entity("Web.Server.Entities.Owner", b =>
                {
                    b.Navigation("Beacons");
                });

            modelBuilder.Entity("Web.Server.Entities.Railroad", b =>
                {
                    b.Navigation("BeaconRailroads");
                });
#pragma warning restore 612, 618
        }
    }
}
