// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Server.Data;

#nullable disable

namespace Web.Server.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260113003219_AddDiscardReasonToTelemetry")]
    partial class AddDiscardReasonToTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Web.Server.Entities.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DpuTrainID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MapPinID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MapPinID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("Web.Server.Entities.BeaconRailroad", b =>
                {
                    b.Property<int>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubdivisionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Milepost")
                        .HasColumnType("REAL");

                    b.Property<bool>("MultipleTracks")
                        .HasColumnType("INTEGER");

                    b.HasKey("BeaconID", "SubdivisionID");

                    b.HasIndex("SubdivisionID");

                    b.ToTable("BeaconRailroads");
                });

            modelBuilder.Entity("Web.Server.Entities.MapPin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Moving")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubdivisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BeaconID", "SubdivisionId");

                    b.ToTable("MapPins");
                });

            modelBuilder.Entity("Web.Server.Entities.MapPinHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Moving")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginalMapPinID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubdivisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("MapPinHistories");
                });

            modelBuilder.Entity("Web.Server.Entities.Railroad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Railroads");
                });

            modelBuilder.Entity("Web.Server.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Web.Server.Entities.Subdivision", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DpuCapable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalTrainAddressIDs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RailroadID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RailroadID");

                    b.ToTable("Subdivisions");
                });

            modelBuilder.Entity("Web.Server.Entities.SubdivisionTrackageRight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSubdivisionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToSubdivisionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("FromSubdivisionID");

                    b.HasIndex("ToSubdivisionID");

                    b.ToTable("SubdivisionTrackageRights");
                });

            modelBuilder.Entity("Web.Server.Entities.Telemetry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscardReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Discarded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Moving")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BeaconID");

                    b.ToTable("Telemetries");
                });

            modelBuilder.Entity("Web.Server.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Web.Server.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Web.Server.Entities.UserTrackedPin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BeaconID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MapPinId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubdivisionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("MapPinId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTrackedPins");
                });

            modelBuilder.Entity("Web.Server.Entities.Address", b =>
                {
                    b.HasOne("Web.Server.Entities.MapPin", "MapPin")
                        .WithMany("Addresses")
                        .HasForeignKey("MapPinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapPin");
                });

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.HasOne("Web.Server.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Web.Server.Entities.BeaconRailroad", b =>
                {
                    b.HasOne("Web.Server.Entities.Beacon", "Beacon")
                        .WithMany("BeaconRailroads")
                        .HasForeignKey("BeaconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Server.Entities.Subdivision", "Subdivision")
                        .WithMany("BeaconRailroads")
                        .HasForeignKey("SubdivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");

                    b.Navigation("Subdivision");
                });

            modelBuilder.Entity("Web.Server.Entities.MapPin", b =>
                {
                    b.HasOne("Web.Server.Entities.BeaconRailroad", "BeaconRailroad")
                        .WithMany()
                        .HasForeignKey("BeaconID", "SubdivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BeaconRailroad");
                });

            modelBuilder.Entity("Web.Server.Entities.Subdivision", b =>
                {
                    b.HasOne("Web.Server.Entities.Railroad", "Railroad")
                        .WithMany("Subdivisions")
                        .HasForeignKey("RailroadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Railroad");
                });

            modelBuilder.Entity("Web.Server.Entities.SubdivisionTrackageRight", b =>
                {
                    b.HasOne("Web.Server.Entities.Subdivision", "FromSubdivision")
                        .WithMany("HasTrackageRights")
                        .HasForeignKey("FromSubdivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Server.Entities.Subdivision", "ToSubdivision")
                        .WithMany("GrantedTrackageRights")
                        .HasForeignKey("ToSubdivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromSubdivision");

                    b.Navigation("ToSubdivision");
                });

            modelBuilder.Entity("Web.Server.Entities.Telemetry", b =>
                {
                    b.HasOne("Web.Server.Entities.Beacon", "Beacon")
                        .WithMany("Telemetries")
                        .HasForeignKey("BeaconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("Web.Server.Entities.UserRole", b =>
                {
                    b.HasOne("Web.Server.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Server.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web.Server.Entities.UserTrackedPin", b =>
                {
                    b.HasOne("Web.Server.Entities.MapPin", "MapPin")
                        .WithMany()
                        .HasForeignKey("MapPinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Server.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapPin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web.Server.Entities.Beacon", b =>
                {
                    b.Navigation("BeaconRailroads");

                    b.Navigation("Telemetries");
                });

            modelBuilder.Entity("Web.Server.Entities.MapPin", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Web.Server.Entities.Railroad", b =>
                {
                    b.Navigation("Subdivisions");
                });

            modelBuilder.Entity("Web.Server.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Web.Server.Entities.Subdivision", b =>
                {
                    b.Navigation("BeaconRailroads");

                    b.Navigation("GrantedTrackageRights");

                    b.Navigation("HasTrackageRights");
                });

            modelBuilder.Entity("Web.Server.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
