// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Server.Data;

#nullable disable

namespace Web.Server.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Web.Server.Models.Telemetry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressID")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "AddressID");

                    b.Property<string>("BeaconID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "BeaconID");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "Longitude");

                    b.Property<bool?>("Moving")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "Moving");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Timestamp");

                    b.Property<int?>("TrainID")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "TrainID");

                    b.HasKey("ID");

                    b.ToTable("Telemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
